### ISSUE TITLE
Getting error for uuid-dev while compiling through cmake on windows OS

### ISSUE THREAD

**Issue by Komal7209** [microsoft/jsonbuilder#21]
![cmakecompileError](https://user-images.githubusercontent.com/33154959/149938557-34cb7fb8-791c-4890-bacb-f31121be9df6.png)

**Comment by Komal7209** [comment]
Hi
@jsmrcina ,  @nickbopp , @bfulper , @microsoftopensource , @msftgits  or @moderators 
Is there anything else which is required to be added so that it could work on windows target machine too apart from linux

**Comment by ekcdd** [comment]
I can confirm this as well. I'm using CLion and tried with mingw and msvc that comes with VS 2022.
